### ISSUE TITLE
DuplicateTestNameException

### ISSUE THREAD

**Issue by triciawang1** [seveniruby/AppCrawler#1]
运行java -jar appcrawler-1.7.1.jar --diff --master Android_20161028114611 --candidate  android_20161028122447 --report diff/
 org.scalatest.exceptions.DuplicateTestNameException:[0m
[31m  at org.scalatest.SuperEngine.registerTest(Engine.scala:660)[0m
[31m  at org.scalatest.FunSuiteLike$class.test(FunSuiteLike.scala:127)[0m
[31m  at org.scalatest.FunSuite.test(FunSuite.scala:1560)[0m
[31m  at com.xueqiu.qa.appcrawler.DiffSuite$$anonfun$addTestCase$1.apply(DiffSuite.scala:36)[0m
[31m  at com.xueqiu.qa.appcrawler.DiffSuite$$anonfun$addTestCase$1.apply(DiffSuite.scala:30)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m
[31m  at com.xueqiu.qa.appcrawler.DiffSuite.addTestCase(DiffSuite.scala:30)[0m
[31m  at com.xueqiu.qa.appcrawler.DiffSuite.<init>(DiffSuite.scala:26)[0m
[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[0m
[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[0m
[31m  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[0m
[31m  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[0m
[31m  at java.lang.Class.newInstance(Class.java:442)[0m
[31m  at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1422)[0m
[31m  at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1236)[0m
[31m  at org.scalatest.tools.Runner$$anonfun$31.apply(Runner.scala:1235)[0m
[31m  at scala.collection.immutable.List.map(List.scala:273)[0m
[31m  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1235)[0m
[31m  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)[0m
[31m  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)[0m
[31m  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)[0m
[31m  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)[0m
[31m  at org.scalatest.tools.Runner$.run(Runner.scala:850)[0m
[31m  at com.xueqiu.qa.appcrawler.Report$class.runTestCase(Report.scala:119)[0m
[31m  at com.xueqiu.qa.appcrawler.Report$.runTestCase(Report.scala:134)[0m
[31m  at com.xueqiu.qa.appcrawler.AppCrawler$.main(AppCrawler.scala:260)[0m
[31m  at com.xueqiu.qa.appcrawler.AppCrawler.main(AppCrawler.scala)[0m

**Comment by seveniruby** [comment]
新版本已经解决.
