### ISSUE TITLE
能够正确的执行testcase里面的代码，然后app不停的重启

### ISSUE THREAD

**Issue by wanderburn** [seveniruby/AppCrawler#11]
`
![1](https://user-images.githubusercontent.com/22465801/36086472-92190a30-1007-11e8-8413-d1d6cabca212.png)
![2](https://user-images.githubusercontent.com/22465801/36086474-9702e87c-1007-11e8-844f-3fcc447be1eb.png)

`

**Comment by benchenglian** [comment]
看看你的配置文件，seleclist，triggerActions，testcase。

**Comment by benchenglian** [comment]
autoCrawl 这个参数是true吗？
